[tool.pytest.ini_options]
testpaths=["tests"]
addopts="-q"

[tool.coverage.run]
branch=true
source=["src"]
omit=[
    "tests/*",
    "**/__init__.py",
]

[tool.coverage.report]
show_missing=true
skip_covered=true
# fail_under=70 <-- for tests to not to fail during development stage